language: c++

compiler:
  - g++

#dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y automake sqlite3 build-essential autoconf libtool git libxml2 libxml2-dev sqlite libsqlite3-dev python-dev libbluetooth-dev libdbus-1-3 libdbus-1-dev libssl-dev
  - export ENCODERS_HOME=`pwd`
  - export COVERALLS_REPO_TOKEN="yNThx10Y07YoE9ul06QvgKm389jMeeUSc"
  - export CXXFLAGS="${CXXFLAGS} -fprofile-arcs -ftest-coverage"
  - sudo pip install --user cpp-coveralls;
  - sudo pip install pyyaml;
  - export PATH=$PATH:${HOME}/.local/bin

script:
  - cd ${ENCODERS_HOME}/haggle 
  - ./autogen.sh
  - ./configure --enable-gcov
  - make 
  - make test_thread 
  
after_script:
  - coveralls -r .. -b . --gcov-options '\-lp';
